
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    apiKey: 'AIzaSyB4YIwLEwoDftH9z_Pc9B8CZlHBjTGyq-4'
  };
